const products = [
    {
        id: 1,
        img: "/img/300/tomahawk-300.jpg",
        img500: "/img/500/tomahawk-500.jpg",
        title: "Tomahawk",
        description: "El tomahawk es un corte tradicional americano. Es ideal para hacer a la parrilla.",
        price: 1990,
        category: "ternera",
        stock: 12,
    },
    {
        id: 2,
        img: "/img/300/costillas-de-cerdo-300.jpg",
        img500: "/img/500/costillas-de-cerdo-500.jpg",
        title: "Costillas de cerdo",
        description: "La costillita de cerdo es ideal para hacerlo a la plancha.",
        price: 990,
        category: "cerdo",
        stock: 6,
    },
    {
        id: 3,
        img: "/img/300/chinchulin-300.jpeg",
        img500: "/img/500/chinchulin-500.jpeg",
        title: "Chinchulin",
        description: "Un clásico de la parrilla, el chinchulin con su textura y sabor particular es infaltable para una parrillada Argentina.",
        price: 550,
        category: "achura",
        stock: 7,
    },
    {
        id: 4,
        img: "/img/300/morcilla-rosca-300.jpeg",
        img500: "/img/500/morcilla-rosca-500.jpeg",
        title: "Morcilla Rosca",
        description: "La morcilla es un producto infaltable para el comienzo del disfrute de una parrillada, se puede consumir fría acompañando una picada o caliente como entrada del plato principal.",
        price: 950,
        category: "achura",
        stock: 8,
    },
    {
        id: 5,
        img: "/img/300/colita-de-cuadril-300.jpg",
        img500: "/img/500/colita-de-cuadril-500.jpg",
        title: "Colita de Cuadril",
        description: "Ideal para hacer al horno o a la parrilla, la colita de cuadril puede hacerse mechada o simplemente enteras",
        price: 1900,
        category: "ternera",
        stock: 9,
    },
    {
        id: 6,
        img: "/img/300/suprema-300.jpg",
        img500: "/img/500/suprema-500.jpg",
        title: "Suprema de pollo",
        description: "La suprema es ideal para hacer a la plancha, versatil para poder agregarle una ssalsa gourmet o para rebozarlas.",
        price: 1150,
        category: "ave",
        stock: 10,
    }
     
]

export default products;